/* D2L page first. Teaching controls are opened only on request. */
let walkthroughTimer=null,walkthroughPlaying=false;
if(!state.interfaceVersion){state.interfaceVersion=2;state.selectedCourse='captured-empty';const seed=state.courses.find(c=>c.id==='captured-empty');if(seed)seed.name='Same Playground';}
view.route='course-admin';
function shellIcon(kind){const paths={home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',grid:'M3 3h4v4H3zM10 3h4v4h-4zM17 3h4v4h-4zM3 10h4v4H3zM10 10h4v4h-4zM17 10h4v4h-4zM3 17h4v4H3zM10 17h4v4h-4zM17 17h4v4h-4z',mail:'M2 5h20v14H2zM2 5l10 8L22 5',message:'M3 3h18v13H11l-6 5v-5H3z',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM9 20h6',gear:'M10 2h4l1 4 4-1 2 4-3 3 3 3-2 4-4-1-1 4h-4l-1-4-4 1-2-4 3-3-3-3 2-4 4 1z'};return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[kind]||paths.home}"/>${kind==='gear'?'<circle cx="12" cy="12" r="3"/>':''}</svg>`;}
function header(){return `<header class="d2l-shell-header"><button type="button" class="shell-icon" data-action="navigate" data-route="home" aria-label="Course Home">${shellIcon('home')}</button><span class="shell-divider"></span><span class="shell-course-title">${h(course().name)}</span><div class="shell-right"><label class="shell-course-picker" title="Select a course">${shellIcon('grid')}<span class="sr-only">Select a course</span><select data-action="course" aria-label="Practice course">${state.courses.map(c=>`<option value="${h(c.id)}"${selected(c.id,course().id)}>${h(c.name)}</option>`).join('')}</select></label><span class="shell-divider"></span>${['mail','message','bell'].map((icon,i)=>`<button type="button" class="shell-icon" disabled title="not modelled" aria-label="${['Message alerts','Subscription alerts','Update alerts'][i]}">${shellIcon(icon)}</button>`).join('')}<span class="shell-divider"></span><span class="shell-user"><span class="shell-avatar">SU</span>Sandbox user <span class="small">▾</span></span><span class="shell-divider"></span><button type="button" class="shell-icon" data-action="admin-unobserved" aria-label="Admin Tools">${shellIcon('gear')}</button></div></header><nav class="navbar faithful-navbar" aria-label="Course tools">${navButton('Course Home','home')}${navButton('Content','content')}${capturedNavbarMenu('Course Tools')}${capturedNavbarMenu('Assessments')}${capturedNavbarMenu('Communication')}${navButton('Help','resources')}${navButton('Course Admin','course-admin')}${capturedNavbarMenu('More')}</nav>`;}
function trainingLauncher(){return `<div class="training-launcher"><span>Local simulation</span>${action('Explain clicks: '+(state.explainClicks?'On':'Off'),'toggle-explanations','aria-pressed="'+!!state.explainClicks+'"','walkthrough-launch-button')}${action('Walkthroughs','open-walkthroughs','','walkthrough-launch-button')}</div>`;}
function home(){return `<div class="faithful-home"><div class="course-banner"><h1>${h(course().name)}</h1></div><div class="home-widgets"><div><section class="home-widget"><h2>Announcements <span>▾</span></h2><p>There are no announcements to display.</p>${action('Create an announcement','course-tool','data-label="Announcements"','link-button')}</section><section class="home-widget"><h2>Updates</h2><p>There are no current updates for ${h(course().name)}</p></section><section class="home-widget"><h2>Content Browser</h2><div class="tabs"><button disabled title="not modelled">Bookmarks</button><button disabled title="not modelled">Recently Visited</button></div><p>${course().content.length?'Sample course content is available.':'There is no content to display.'}</p>${action('Create some content','navigate','data-route="content"','link-button')}</section><section class="home-widget"><h2>Course Overview</h2><p class="muted">Analytics are not modeled in this local file.</p><div class="row"><button disabled title="not modelled">Class Engagement</button><button disabled title="not modelled">Course Access</button><button disabled title="not modelled">Tool Access...</button></div></section></div><div><section class="home-widget"><h2>Role Switch</h2><label class="field"><span>Current Role</span><select disabled title="not modelled"><option>-- My Role (OrgUnit Admin) --</option></select></label><button disabled title="not modelled">Change Role</button></section><section class="home-widget"><h2>Need Help?</h2>${action('D2L Help Site','navigate','data-route="resources"','link-button')}<p>Educational Technology Training</p></section><section class="home-widget"><h2>Calendar</h2><h3>Upcoming events</h3><p>There are no events to display</p></section><section class="home-widget"><h2>Library Resources</h2><p>Research & Course Guides</p><input disabled placeholder="Library Search" title="not modelled"><p>Need Help? Ask A Librarian</p></section><section class="home-widget"><h2>MSU Toolbox</h2><p class="small">Grade Submission: Only Course Admins, Course Editors and Course Assistants can submit grades to registrar.</p><p class="small muted">Registrar submission and Large Course Tools are not modeled.</p></section></div></div></div>`;}
function replayPage(){const s=replay.tour.steps[replay.index];return `<div id="replay-screen" class="faithful-replay">${renderReplayBlocks(resolveReplayScreen(replay.tour,s.screen))}</div>`;}
function gradePage(){const sub=view.tab,settings=['personal','display','calculation'].includes(sub);if(settings)return `<h1>${({personal:'Personal Display Options',display:'Org Unit Display Options',calculation:'Calculation Options'})[sub]}</h1>${gradeSettings()}`;const body=sub==='enter'?enterGrades():sub==='manage'?manageGrades():sub==='schemes'?schemes():sub==='wizard'?wizardPage():sub==='finals'?finalGradesPage():enterGrades();return `<div class="grade-navigation">${tabs([['enter','Enter Grades'],['manage','Manage Grades'],['schemes','Schemes'],['wizard','Setup Wizard']],sub,'grade-tab')}<div class="actions">${action('⚙ Settings','grade-tab','data-tab="personal"')}${action('Help','capture-open','data-id="grades-enter-grades"')}</div></div>${sub==='finals'?'<h1>Final Grades</h1>':''}${body}`;}
function openWalkthroughMenu(){stopReplay();walkthroughPlaying=false;clearTimeout(walkthroughTimer);openDialog('Walkthroughs & ticket reference',`${supportPanel()}<details class="accordion"><summary>Browse all walkthroughs and recordings</summary><div class="stack">${action('Play the recorded MSU gradebook session','start-recorded-replay','','primary')}<label class="field"><span>Load another recorded tour (.json)</span><input type="file" id="replay-file" accept=".json,application/json"></label>${replay.error?`<p class="callout warn">${h(replay.error)}</p>`:''}<h3>Support ticket sequences</h3>${WORKFLOWS.map(t=>action(h(t.title),'launch-working-tour',`data-id="${h(t.id)}"`)).join('')}<details class="accordion"><summary>Reference library and local resources</summary><div class="stack">${action('Browse the 47 captured screens','launch-resource','data-route="library"')}${action('Learning notes and AI instructions','launch-resource','data-route="resources"')}${action('Calculation self-check','launch-resource','data-route="self-check"')}${action('General admin exercises · not captured at MSU','launch-resource','data-route="admin"')}${action('Export learning notebook','export')}${action('Reset local simulation','reset')}</div></details></div></details>`);}
function activeWalkthrough(){if(view.route==='replay'){const t=replay.tour,s=t.steps[replay.index];return {recorded:true,id:s.id,title:s.title||s.target,body:s.card,action:s.actionLabel||s.action,index:replay.index,total:t.steps.length,date:t.recorded,evidence:s.evidence||'unprovided',target:s.target,playing:replay.playing,correction:t.tour_id===CAPTURE_TOUR.tour_id?REPLAY_CORRECTIONS[s.id]:null};}if(view.tour){const t=WORKFLOWS.find(t=>t.id===view.tour),s=t.steps[view.step];return {recorded:false,title:s.title,body:s.body,action:'Make the change when you are ready. Next advances the explanation; it does not save the form.',index:view.step,total:t.steps.length,date:'2026-09-22',evidence:'documented practice model',target:s.target,playing:walkthroughPlaying,route:s.route,tab:s.tab};}return null;}
function walkthroughTarget(active){if(!active)return null;if(active.recorded){const all=[...document.querySelectorAll('#replay-screen [data-replay-label]')];return all.find(e=>e.dataset.replayLabel===active.target)||(!active.target.includes(':')?all.find(e=>['menu:'+active.target,'dialog:'+active.target].includes(e.dataset.replayLabel)):null);}if(active.route!==view.route||active.tab&&active.tab!==view.tab)return null;return document.querySelector(`[data-target="${active.target}"]`);}
function updateWalkthroughOverlay(scroll=false){const active=activeWalkthrough();let box=document.getElementById('walkthrough-box');if(!active){box?.remove();return;}if(!box){box=document.createElement('div');box.id='walkthrough-box';box.className='walkthrough-box';document.body.append(box);}const key=(active.recorded?'replay':'practice')+':'+active.index+':'+active.title+':'+active.playing;if(box.dataset.stepKey!==key){box.dataset.stepKey=key;box.innerHTML=`<div class="walkthrough-box-heading"><span>STEP ${active.index+1} / ${active.total}</span><span>${action('−','minimize-walkthrough','aria-label="Minimize or expand explanation"','quiet')}${action('×','dismiss-walkthrough','aria-label="Close walkthrough"','quiet')}</span></div><h2>${h(active.title)}</h2><div class="walkthrough-explanation"><p class="notes">${h(active.body)}</p>${active.correction?`<div class="callout warn"><b>Review correction</b><p>${h(active.correction)}</p></div>`:''}${active.recorded?`<p class="small"><b>Action:</b> ${h(active.action||'Look')}</p>`:''}<p class="walkthrough-evidence">${active.recorded?'Recorded':'Prepared'} ${h(active.date||'date unprovided')} · ${h(active.evidence)}${active.recorded?' (author-reported)':''}</p></div><div class="walkthrough-box-controls">${active.recorded?action(active.playing?'Pause':'Play','walkthrough-play'):'<span class="small muted">At your pace</span>'}${action('Back','walkthrough-back',active.index===0?'disabled':'')}${action(active.index===active.total-1?'Finish':'Next →','walkthrough-next','','primary')}<button type="button" class="quiet" data-action="walkthrough-restart" title="Restart sequence">↺</button></div><p id="walkthrough-target-status" class="walkthrough-status"></p>`;}
 const target=walkthroughTarget(active);document.querySelectorAll('.tour-target').forEach(e=>e.classList.remove('tour-target'));document.getElementById('tour-popover').hidden=true;if(target)target.classList.add('tour-target');const status=box.querySelector('#walkthrough-target-status');status.textContent=target?'':'Target not found on this screen: '+active.target;if(document.getElementById('dialog').open){box.hidden=true;return;}box.hidden=false;
 if(scroll&&target)target.scrollIntoView({block:'start',behavior:'instant'});positionWalkthroughBox(box,target);
}
function positionWalkthroughBox(box,target){
 const gap=16,w=Math.min(390,innerWidth-24),body=box.querySelector('.walkthrough-explanation,.click-explanation-body');box.style.width=w+'px';box.style.maxHeight='calc(100vh - 24px)';if(body)body.style.maxHeight='';
 let height=box.offsetHeight,left=innerWidth-w-gap,top=innerHeight-height-gap;
 if(target){const r=(target.closest('form')||target).getBoundingClientRect(),right=innerWidth-r.right-gap*2,leftSpace=r.left-gap*2,above=r.top-gap*2,below=innerHeight-r.bottom-gap*2;
  if(right>=w){left=r.right+gap;top=Math.max(gap,Math.min(r.top,innerHeight-height-gap));}
  else if(leftSpace>=w){left=r.left-w-gap;top=Math.max(gap,Math.min(r.top,innerHeight-height-gap));}
  else {let useBelow=below>=height||below>=above,space=Math.max(0,useBelow?below:above);if(space<height&&body&&space>190){const overhead=height-body.offsetHeight;body.style.maxHeight=Math.max(75,space-overhead)+'px';height=box.offsetHeight;}if(space>=height-2){left=Math.max(gap,Math.min(r.left,innerWidth-w-gap));top=useBelow?r.bottom+gap:r.top-height-gap;}}
 }
 box.style.left=Math.max(12,left)+'px';box.style.top=Math.max(12,top)+'px';
}
function highlight(scroll){updateWalkthroughOverlay(scroll);}
function dismissWalkthrough(){stopReplay();walkthroughPlaying=false;clearTimeout(walkthroughTimer);if(view.tour&&!state.completed.includes(view.tour)&&view.step===WORKFLOWS.find(t=>t.id===view.tour).steps.length-1){state.completed.push(view.tour);persist();}view.tour=null;if(view.route==='replay')view.route='course-admin';render();}
function armWorkingTour(){clearTimeout(walkthroughTimer);if(!walkthroughPlaying||!view.tour)return;walkthroughTimer=setTimeout(()=>{const t=WORKFLOWS.find(t=>t.id===view.tour);if(!t){walkthroughPlaying=false;return;}if(view.step<t.steps.length-1){view.step++;showStep();armWorkingTour();}else{walkthroughPlaying=false;render();}},18000);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;try{
 if(a==='minimize-walkthrough'){document.getElementById('walkthrough-box')?.classList.toggle('is-minimized');updateWalkthroughOverlay(false);}
 else if(a==='open-walkthroughs')openWalkthroughMenu();
 else if(a==='start-recorded-replay'){closeDialog();view.route='replay';view.tour=null;replay.index=0;replay.playing=false;render();requestAnimationFrame(()=>updateWalkthroughOverlay(true));}
 else if(a==='launch-working-tour'){closeDialog();if(['grade-setup','blank-zero','release-final','content-hidden','assignment-dates','quiz-special','course-accommodation'].includes(b.dataset.id)&&!course().items.length){const example=state.courses.find(c=>c.items.length);if(example)state.selectedCourse=example.id;}startTour(b.dataset.id);}
 else if(a==='launch-resource'){closeDialog();navigate(b.dataset.route);}
 else if(a==='admin-unobserved')openDialog('Admin Tools',`<p>The organization-wide Admin Tools menu was not opened in the capture. Its contents cannot be reconstructed accurately from the supplied material.</p><div class="savebar">${action('Open general admin exercises','launch-resource','data-route="admin"')}${action('Close','close-dialog')}</div>`);
 else if(a==='dismiss-walkthrough')dismissWalkthrough();
 else if(a==='walkthrough-play'){if(view.route==='replay'){if(replay.playing)stopReplay();else replay.playing=true;render();armReplay();}else{walkthroughPlaying=!walkthroughPlaying;render();armWorkingTour();}}
 else if(a==='walkthrough-back'){if(view.route==='replay'){setReplayIndex(Math.max(0,replay.index-1));requestAnimationFrame(()=>updateWalkthroughOverlay(true));}else{walkthroughPlaying=false;clearTimeout(walkthroughTimer);view.step=Math.max(0,view.step-1);showStep();}}
 else if(a==='walkthrough-next'){const active=activeWalkthrough();if(active.index===active.total-1){dismissWalkthrough();return;}if(active.recorded){setReplayIndex(replay.index+1);requestAnimationFrame(()=>updateWalkthroughOverlay(true));}else{walkthroughPlaying=false;clearTimeout(walkthroughTimer);view.step++;showStep();}}
 else if(a==='walkthrough-restart'){if(view.route==='replay')setReplayIndex(0);else{view.step=0;showStep();}}
 }catch(err){toast(err.message);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.getElementById('dialog').open&&activeWalkthrough())dismissWalkthrough();});
// Review fixes preserve the imported evidence while keeping known errors out of the lesson.
const REVIEWED_REPLAY_CARDS={
 'undo-tick-quizzes':'WHAT: this page selects grade items and categories for deletion. A category is a container; removing it leaves its items outside the category.\n\nTICKET: “I created the wrong category.” Check whether the educator wants the container removed or its items removed as well. Those are different changes.\n\nRECOVERY: eligible deleted grade items can be restored from Manage Grades → More Actions → View Event Log → Restore, subject to item type and permissions. An associated activity may need to be unlinked before its grade item can be deleted.',
 'undo-confirm-delete':'WHAT: the confirmation applies the selected deletion. Review the selected names and whether each is a category or a grade item.\n\nTICKET: “I accidentally deleted the grade column.” Eligible Numeric, Selectbox, Pass/Fail, and Text items can be restored through Manage Grades → More Actions → View Event Log. Do not assume that every deletion is permanent or that every deleted object is recoverable.\n\nIn this recording, the next screen shows the reported result. Playback does not delete your local gradebook items.',
 'wiz-4-scheme':'WHAT: the default grade scheme maps grades to displayed values, such as percentages or letter grades. Percentage was the organization scheme in this capture.\n\nDISTINCTION: for Numeric items, changing the scheme changes the displayed symbol rather than the earned points. Selectbox items are different: the scheme’s Assigned Value percentage participates in their calculation.\n\nTICKET: “The percentage is correct, but the letter grade is wrong.” Check the selected scheme and its ranges before changing the learner’s score.',
 'undo-calc-tab':'WHAT: Calculation Options contains the grading system, the final-grade type to release, the treatment of ungraded items, and automatic update options.\n\nTICKET: “The final is displaying out of 240.” That denominator alone does not establish that the grading system is wrong. First compare the intended course calculation, item maximums, weights, and display options.\n\nWeighted uses percentage contributions; Points uses earned points divided by possible points. Choose the system that matches the course design, then check a known learner calculation.',
 'undo-confirm-save-2':'WHAT: this is the second confirmation reported when saving a grading-system change in the captured MSU course.\n\nWHY: changing the system can change final calculations even though the entered scores remain the same. Review one known learner’s total after the save.\n\nThe setting is reversible; the important question is whether the new system matches the intended gradebook. Do not assume every institution or version presents the same two confirmations.',
 'wiz-7-finish':'WHAT: the summary brings together the grading system, release type, ungraded-item policy, scheme, and display choices.\n\nWHY: this is a useful checkpoint for a new course. A correct item structure can still produce an unexpected result when its calculation policy differs from the syllabus.\n\nFinish was reported to save this captured run and open Grade Options. The working wizard in this file keeps a draft until Finish; that draft behavior is a local implementation, not something established for every real Brightspace wizard.'
};
const originalActiveWalkthrough=activeWalkthrough;
activeWalkthrough=function(){const a=originalActiveWalkthrough();if(a?.recorded&&replay.tour.tour_id===CAPTURE_TOUR.tour_id&&REVIEWED_REPLAY_CARDS[a.id]){a.body=REVIEWED_REPLAY_CARDS[a.id];a.correction=null;a.evidence='capture with documentation corrections';}return a;};
