/* Optional, local click explanations. No network requests or AI calls. */
const HELP_SOURCE='https://community.d2l.com/brightspace/kb/articles/3539-set-up-your-grade-book';
const simpleHelp=(what,steps,result,ticket,source=HELP_SOURCE)=>({what,steps,result,ticket,source});
const PAGE_HELP={
 'Course Admin':simpleHelp('The course-level directory of tools and settings, grouped by function. Institution-wide user management and role definitions belong to Admin Tools instead.',['Under Assessment, click Grades to work on marks.','Under Site Resources, click Content to work on lesson materials.','Use Category to keep tools grouped by purpose; Name puts them in alphabetical order.'],'The available tools depend on the course, institutional configuration, and your role.','“Where do I change this course’s settings?”'),
 'Course Home':simpleHelp('The course landing page combines widgets such as Announcements, Calendar, and Content Browser. Homepages and Widgets control its structure.',['Read Announcements for course notices.','Use the top navigation bar to open a tool such as Content.'],'A missing widget and missing content inside a widget are separate issues: check the active homepage first, then the source tool or release conditions.','“Where is the announcement my instructor posted?”'),
 'Enter Grades':simpleHelp('This page is for entering learner scores. A grade item is one column, such as Quiz 1.',['Find the learner’s row and the assessment’s column.','Enter the score earned, not a percentage unless the item is out of 100.','Click Save grades below the grid.'],'The saved score is used in the calculated final. A blank and a score of zero have different meanings.','“I need to enter 8 out of 10 for one student.”'),
 'Manage Grades':simpleHelp('This page builds the gradebook: the columns, categories, maximum points, and weights.',['Click New → Item → Numeric to add a score column.','Click New → Category to group columns, such as weekly quizzes.','Click an existing blue item name to edit it.'],'The item appears as a column in Enter Grades. Creating a column does not enter learner scores.','“How do I add a final project worth 30%?”'),
 'Setup Wizard':simpleHelp('The wizard asks the basic gradebook setup questions one page at a time.',['Click Start.','Choose each option, then click Continue. Back returns to the previous question.','Review the summary, then click Finish.'],'In this file, Finish saves the setup. Continue moves through the draft choices.','“I have a new course and no gradebook yet.”'),
 'Schemes':simpleHelp('A grade scheme converts a number into a displayed symbol, such as a letter grade.',['Open the practice scheme and inspect each starting percentage.','For example, a row starting at 80 means that range begins at 80%.','Save after changing the ranges.'],'For numeric items, changing the scheme changes the displayed symbol, not the earned points. Selectbox items use different calculation rules and are not simulated here.','“Why is 82% displaying a B instead of an A?”','https://community.d2l.com/brightspace/kb/articles/34122-create-grading-schemes-using-the-grades-tool'),
 'Personal Display Options':simpleHelp('These are your own instructor-view preferences for the Grades page.',['Check Username or Org Defined ID if you need those identifiers beside learner names.','Choose the grade details you want to see.','Click Save.'],'These preferences do not release grades to learners. This file renders only the supported preferences described on the page.','“Can I see student IDs beside names while entering marks?”'),
 'Org Unit Display Options':simpleHelp('Org Unit means this course. This tab includes the course’s default grade display, including student-view options.',['Under Student View Display Options, choose Points grade, Weighted grade, or Grade scheme symbol.','Set the number of decimal places to display.','Click Save.'],'These options affect how grades are displayed. Final-grade release is a separate decision.','“Students should see their mark out of 20 as well as the letter grade.”'),
 'Calculation Options':simpleHelp('This tab decides how Brightspace calculates the final grade and which final-grade type can be released.',['Read Grading System first: Weighted uses percentages; Points adds earned and possible points.','Read Grade Calculations to decide how empty score cells behave.','Click Save. If changing systems, review both captured confirmation dialogs.'],'The saved settings control calculated finals. They do not change the scores you entered.','“Why does the final grade not match my spreadsheet?”'),
 'Assessments':simpleHelp('Assessment tools cover activity creation, evaluation, and the gradebook. Assignments handles submitted work; Quizzes handles tests; Grades holds the scored items and final calculation.',['Click Grades for the gradebook.','Click Assignments for submitted work, or Quizzes for tests.'],'An assessment’s gradebook association connects the activity to a grade item; the activity settings and grade item settings still serve different purposes.','“Where do I find the quiz settings?”'),
 'Course Tools':simpleHelp('This menu collects course tools selected for the institution’s navigation bar.',['Read the tool names in the dropdown.','Click the tool you need; Course Admin also provides a grouped directory.'],'A missing navbar link does not necessarily mean the tool is disabled. Compare Course Admin → Tools and Navigation & Themes, subject to your permissions.','“The tool I need is not on the main navigation bar.”'),
 'Communication':simpleHelp('This menu contains tools for course notices and conversations.',['Choose Announcements for a notice shown to the course.','Choose Discussions for a forum where learners post and reply.'],'For visibility tickets, check the item’s dates and release conditions. A visible announcement is separate from whether a learner receives a notification.','“Should I post this as a notice or a discussion?”'),
 'More':simpleHelp('This menu holds additional links from the captured MSU navigation bar.',['Open the menu and read its links.','Select the named tool, or use Course Admin to find course tools by category.'],'The captured menu is institution-specific; additional tools may also be available through Course Admin.','“I cannot find a tool in the first few navigation links.”')
};
const FIELD_HELP={
 mode:simpleHelp('The grading system is the rule used to combine the gradebook scores.',['Choose Weighted if the syllabus says categories contribute percentages, such as Quizzes 40% and Project 60%.','Choose Points if the syllabus adds earned points and divides by all possible points.','Save. If asked, read and answer the two system-change confirmations.'],'With the sample scores, Weighted gives 82%; Points gives 104 ÷ 120 = 86.67%. The scores are unchanged.','“Why are the same marks giving two different final percentages?”'),
 blanks:simpleHelp('An ungraded item has an empty score cell. It has no entered mark yet.',['Choose Drop/Exclude ungraded items to leave empty cells out of the current total.','Choose Treat ungraded items as 0 to count empty cells as zero.','Save, then compare the calculated final in Enter Grades.'],'With Demo Learner’s Quiz 2 blank in the sample weighted course, excluding it gives 86%; counting it as zero gives 70%. An entered 0 counts as zero with either choice.','“A student’s current average seems too high because work is missing.”'),
 finalType:simpleHelp('Calculated Final Grade comes from the gradebook rules. Adjusted Final Grade is a separate final value the instructor can set.',['Choose Calculated if the gradebook total is the final you intend to show.','Choose Adjusted only if you intend to maintain that separate final value.','Save, then use Final Grades to release the selected type.'],'Selecting a final type does not, by itself, release it to every learner.','“I entered an adjusted final, but the student still sees the calculated one.”'),
 autoUpdate:simpleHelp('This controls whether the calculated final is refreshed after scores or calculation settings change.',['Leave it checked when you want calculated finals to update automatically.','If it is unchecked, use Recalculate after saving score changes in this simulator.'],'The calculated final reflects the saved scores when it is recalculated. An adjusted final remains separate.','“I changed a quiz score, but the final total stayed the same.”'),
 autoRelease:simpleHelp('Automatic release concerns showing the selected final grade to learners. It is different from recalculating that number.',['Check which final type is selected above.','For existing learners in this file, open Final Grades and use the Released boxes or Release All, then Save.'],'This simulator uses automatic release as a default for new final-grade records and preserves existing release choices. Check the actual course’s behavior when resolving a real ticket.','“The final grade exists, but students cannot see it.”'),
 due:simpleHelp('Due Date is the deadline used to identify late work. It does not by itself close submissions.',['For a Friday deadline, enter Friday’s date and the required time.','Check End Date separately if submissions must close later.','Click Save and Close.'],'For example, due Friday and ending Sunday allows submissions over the weekend, but they are late after Friday’s deadline.','“Students submitted after the due date. Is that a bug?”','https://community.d2l.com/brightspace/kb/articles/3608-create-an-assignment'),
 start:simpleHelp('Start Date is when availability begins. The exact visibility before that date can also depend on the activity’s availability options.',['Enter the date and time access should begin.','Check visibility and any other access conditions on the actual activity.','Save the form.'],'This simulator shows the activity as upcoming until the start date. It models a limited set of access rules.','“Students can see the assignment title but cannot start yet.”','https://community.d2l.com/brightspace/kb/articles/3608-create-an-assignment'),
 end:simpleHelp('For an assignment, End Date controls the end of the submission window. For a course or module, it controls that object’s modeled availability.',['Confirm which object you are editing: assignment, module, or course.','Enter the intended closing date and time.','Save and check the affected learner’s access.'],'An assignment with a Friday due date and Sunday end date can accept late work until Sunday in this simulator.','“I want the work due Friday but submissions open until Sunday.”','https://community.d2l.com/brightspace/kb/articles/3608-create-an-assignment'),
 minutes:simpleHelp('This is the quiz’s normal duration in minutes, before learner-specific timing rules.',['Enter 30 for a half-hour quiz.','For extra time for just one learner on this quiz, use Manage Special Access instead of changing everyone’s base time.','Save and Close.'],'A base time change affects the quiz’s normal time. Individual overrides may still take precedence.','“Only one student needs 45 minutes on our 30-minute quiz.”'),
 multiplier:simpleHelp('A multiplier scales the original quiz time. 1.5 means one and a half times the original duration.',['Check Modify Time Limit.','Select Multiplier of original quiz time and enter 1.5.','Save the learner’s accommodations.'],'For a 30-minute quiz, 30 × 1.5 = 45 minutes. A quiz-specific timing override can take precedence.','“This student needs 50% extra time on every quiz in this course.”'),
 extraMinutes:simpleHelp('Extra time adds a fixed number of minutes to the original quiz time.',['Check Modify Time Limit.','Select Extra time and enter the number of additional minutes.','Save the accommodation.'],'Adding 15 minutes makes a 30-minute quiz last 45 minutes and a 60-minute quiz last 75 minutes. This is different from multiplying both by 1.5.','“Add 15 minutes to each quiz for this learner.”'),
 hidden:simpleHelp('Hiding a grade item controls learner visibility. It does not remove that item from the calculation.',['Check Hidden from learners to conceal the item.','If the mark must also stop affecting the total, inspect Exclude from calculation separately.','Save the item.'],'A hidden grade can still contribute to the final grade.','“A hidden quiz is still changing the final total.”'),
 excluded:simpleHelp('Exclude from calculation removes this item’s contribution to the calculated final in this simulator.',['Use this only if the item should not count toward the final.','Save, then check the calculated final in Enter Grades.'],'The score can remain stored even though its contribution is excluded. Visibility is a separate setting.','“We recorded a diagnostic quiz but it should not affect the final grade.”'),
 max:simpleHelp('Maximum points is the highest normal score for this item, before any Can Exceed setting.',['For a quiz marked out of 20, enter 20.','Check existing learner scores before changing an item’s maximum.','Save and inspect a sample learner’s percentage.'],'A score of 15 out of 20 is 75%. Changing the maximum changes what the existing score means.','“This assignment was out of 20, but the gradebook says out of 10.”'),
 weight:simpleHelp('Weight is the percentage contribution of an item or category in a weighted gradebook.',['For a top-level project worth 30% of the course, enter 30.','For an item inside a category, its weight is a share of that category.','Save and check that the top-level weights total 100%.'],'An item worth 50% inside a category worth 40% contributes 20% of the whole course when the category is complete.','“Does 50% on this quiz mean half of the course grade?”'),
 decimals:simpleHelp('This controls the number of digits shown after the decimal point in the student view.',['Enter 2 to display 82.35 rather than 82.4.','Click Save.'],'Display rounding does not change the stored calculation precision in this simulator.','“Can students see two decimal places in their marks?”'),
 managingDecimals:simpleHelp('This controls the decimal places shown to staff managing grades.',['Enter the number of digits you want after the decimal point.','Click Save.'],'The displayed staff value is rounded; the underlying calculation keeps its precision.','“I want more precise totals while checking the gradebook.”')
};
let clickContext=null;
function clearClickExplanation(){document.getElementById('click-explanation')?.remove();document.querySelectorAll('.explain-target').forEach(e=>e.classList.remove('explain-target'));clickContext=null;}
function helpBody(info){return `<p><b>Purpose</b><br>${h(info.what)}</p><b>Workflow</b><ol>${info.steps.map(s=>`<li>${h(s)}</li>`).join('')}</ol><p><b>Key distinction</b><br>${h(info.result)}</p><p><b>Typical ticket</b><br>“${h(info.ticket.replace(/^[“"]|[”"]$/g,''))}”</p>${info.scope?`<p class="small muted">${h(info.scope)}</p>`:''}${info.source?`<a class="small" href="${h(info.source)}" target="_blank" rel="noopener">Read the supporting documentation ↗</a>`:''}`;}
function explanationFor(el){const name=el.name||'',text=(el.dataset.label||el.getAttribute('aria-label')||el.closest('label')?.textContent||el.textContent||'').replace(/[⚙▾]/g,'').trim();const title=el.dataset.tab?({enter:'Enter Grades',manage:'Manage Grades',personal:'Personal Display Options',display:'Org Unit Display Options',calculation:'Calculation Options',wizard:'Setup Wizard',schemes:'Schemes',finals:'Final Grades'})[el.dataset.tab]:text;
 if(name.startsWith('minutes:'))return {title:'New Time Limit · special access',info:simpleHelp('This is the full duration for this learner on this quiz, in minutes. It replaces the applicable base or accommodated duration.',['For a 30-minute quiz with a 50% allowance, enter 45, not 15 or 1.5.','Leave this field blank in the simulator to remove the override and use the course accommodation.'],'A 45-minute override remains 45 minutes even if the learner also has a course multiplier.','The student’s extra time was applied twice, or the wrong time is showing.')};
 if(FIELD_HELP[name.split(':')[0]])return {title:text||name,info:FIELD_HELP[name.split(':')[0]]};
 if(TOOL_HELP[title]||PAGE_HELP[title])return {title,info:TOOL_HELP[title]||PAGE_HELP[title]};
 if(el.dataset.action==='menu'){const title=el.dataset.menu.replace('captured-','');if(PAGE_HELP[title])return {title,info:PAGE_HELP[title]};}
 if(el.dataset.action==='final-column-menu'||el.dataset.tab==='finals'||el.dataset.action==='final-title-menu'||name.startsWith('released:'))return {title:'Release a final grade',info:simpleHelp('Release means allow that learner to see the selected final grade. It does not change the number.', ['From Enter Grades, open View Actions for Final Calculated Grade → Enter Grades.','Tick Released for the intended learner, or choose Final Grades → Release All.','Click Save.'],'The simulated learner view shows the final only when it has been released.','“The student sees assignment scores but no final grade.”')};
 if(el.dataset.action==='assignment-special')return {title:'Special access for one assignment',info:simpleHelp('Assignment special access gives selected learners different availability dates for this assignment.',['Identify whether the extension changes the due date, the submission cutoff, or both.','Set the learner’s date overrides in Manage Special Access; blank fields inherit normal dates in this file.'],'A later due date changes when work is late; a later end date extends the submission window. Quiz timing is a separate setting.','One learner needs a two-day extension on the essay.','https://community.d2l.com/brightspace/kb/articles/3608-create-an-assignment')};
 if(el.dataset.action==='special'||el.dataset.action==='quiz-special-users')return {title:'Special access for one quiz',info:simpleHelp('Special access is an exception for named learners on this one quiz.',['Click Add Users to Special Access.','Choose the learner and enter the full New Time Limit, such as 45 minutes for a 30-minute quiz with 50% extra time.','Save the special access.'],'That learner uses 45 minutes on this quiz. Other quizzes keep their own timing rules.','“One student needs extra time on the midterm only.”')};
 if(el.dataset.action==='grade-event-log')return {title:'Restore an eligible deleted grade item',info:simpleHelp('The event log records gradebook changes and can offer Restore for eligible deleted items.',['In Manage Grades, click More Actions → View Event Log.','Find the deleted item and click Restore if available.'],'The item returns to the gradebook. Availability depends on item type and permissions in real Brightspace.','“I accidentally deleted a grade column.”','https://community.d2l.com/brightspace/kb/articles/34138-managing-event-logs-in-grade-book')};
 const screen=CAPTURE.screens.find(s=>s.id===view.captureId),control=screen?.controls?.find(c=>c.label===text&&c.notes);
 if(control)return {title:text,info:simpleHelp(control.notes,['Read the recorded control and its notes on this reference screen.','Use an available recorded transition to follow the next captured screen.'],'This reference does not save live course changes. Uncaptured behavior is not assumed.','“Where is this control, and what was observed when it was opened?”','')};
 return null;
}
function showClickExplanation(context){clearClickExplanation();if(!state.explainClicks||activeWalkthrough()||!context)return;clickContext=context;const dialog=document.getElementById('dialog'),box=document.createElement('section');box.id='click-explanation';box.className='walkthrough-box click-explanation';box.setAttribute('aria-label','Explanation of '+context.title);box.innerHTML=`<div class="walkthrough-box-heading"><span>EXPLAIN CLICKS</span>${action('×','close-explanation','aria-label="Close explanation"','quiet')}</div><h2>${h(context.title)}</h2><div class="click-explanation-body">${helpBody(context.info)}</div>`;
 if(dialog.open){box.classList.add('in-dialog');dialog.append(box);box.scrollIntoView({block:'nearest'});return;}
 document.body.append(box);let target=context.element?.isConnected?context.element:null;if(!target&&context.label)target=[...document.querySelectorAll('[data-label],.tabs button,.navitem')].find(e=>(e.dataset.label||e.textContent).replace(/[⚙▾]/g,'').trim()===context.label);target??=document.querySelector('#main h1,#main h2');context.target=target;if(target)target.classList.add('explain-target');positionWalkthroughBox(box,target?.closest('.dropdown')?.querySelector('.menu')||target);
}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='toggle-explanations'){state.explainClicks=!state.explainClicks;persist();clearClickExplanation();const b=e.target.closest('button');b.textContent='Explain clicks: '+(state.explainClicks?'On':'Off');b.setAttribute('aria-pressed',!!state.explainClicks);toast(state.explainClicks?'Explain clicks is on. Click a course tool or grade setting for a plain-language explanation.':'Explain clicks is off.');return;}if(a==='close-explanation'){clearClickExplanation();return;}});
document.addEventListener('click',e=>{if(e.target.closest('#click-explanation,#walkthrough-box,.training-launcher'))return;if(!state.explainClicks||activeWalkthrough())return;const el=e.target.closest('button,input,select,summary,a');if(!el)return;const context=explanationFor(el);clearClickExplanation();if(context)setTimeout(()=>showClickExplanation({...context,element:el,label:context.title}),0);},true);
const originalHighlight=highlight;
highlight=function(scroll){originalHighlight(scroll);if(activeWalkthrough())clearClickExplanation();};
window.addEventListener('resize',()=>{const box=document.getElementById('click-explanation');if(box&&!box.classList.contains('in-dialog'))positionWalkthroughBox(box,clickContext?.target);});
window.addEventListener('scroll',()=>{const box=document.getElementById('click-explanation');if(box&&!box.classList.contains('in-dialog'))positionWalkthroughBox(box,clickContext?.target);},{passive:true});
document.getElementById('dialog').addEventListener('close',clearClickExplanation);
Object.assign(FIELD_HELP,{
 bonus:simpleHelp('A bonus item can add earned credit without adding its maximum points to the regular denominator.',['Check the bonus item’s maximum points and its course/category placement.','Check Can Exceed on the containing category and final grade if totals above 100% should be permitted.'],'A bonus item can still be capped by its category or final-grade limit. Partial weighted bonus combinations are deliberately not calculated by this file.','Extra credit is entered, but the final grade stops at 100%.','https://help.d2l.msu.edu/msu-docs/d2l-grades-at-msu/d2l-gradebook-extra-credit'),
 dropLowest:simpleHelp('Drop lowest removes a specified number of eligible low scores within a category.',['Group the relevant items in one category and check their points and distribution.','Enter the number of lowest items to drop; compare the affected learner’s calculation.'],'This file supports completed equal-point/equal-weight categories. It reports unsupported combinations instead of inventing a final.','The lowest quiz is supposed to be dropped, but the category total looks wrong.','https://community.d2l.com/brightspace/kb/articles/6122-drop-the-lowest-grade'),
 gradeItem:simpleHelp('The association links an activity to its gradebook column. The activity and the column can have different names.',['Inspect which grade item is linked before creating another column.','Compare the activity’s score scale with the grade item maximum and check whether evaluations are published.'],'This file stores the link only. It does not transfer activity scores or simulate submission evaluation.','The assignment is graded but its gradebook column is empty.','https://community.d2l.com/brightspace/kb/articles/3608-create-an-assignment'),
 visible:simpleHelp('Visibility controls whether learners can see the activity. Availability dates and release conditions can impose additional restrictions.',['Check visibility first, then the start/end dates.','For a real learner, also inspect release conditions, group/section restrictions, and any individual exceptions.'],'Staff may see an activity even when the learner cannot. The simulated learner view implements only the rules listed on this page.','I see the assignment but the student cannot.'),
 canExceed:simpleHelp('Can Exceed allows the relevant item or category to exceed its normal maximum.',['Check the control at the level that is capping the result: item, category, or final.','Compare the earned score with the normal maximum and inspect bonus settings.'],'Allowing an item to exceed does not automatically remove a category or final cap.','The extra-credit score is saved, but it is being capped.'),
 showPoints:simpleHelp('Points grade displays the earned and maximum points, such as 8 / 10.',['In Personal Display Options, this is a staff-view preference.','In Org Unit Display Options, Student View Display Options controls the learner-facing display.'],'Display choices do not release the final grade or alter the gradebook math.','Students need to see their raw score out of 10.'),
 showPercent:simpleHelp('Weighted grade displays the contribution earned toward the item’s configured weight.',['Compare the item’s maximum points with its weight and its category’s weight.','For an 8/10 item worth 20% of the course, the contribution is 16/20.'],'An earned weight is not the same thing as the raw score or percentage on the assessment.','Why does the student see 16 / 20 when I entered 8 / 10?'),
 showScheme:simpleHelp('Grade scheme symbol displays the mapped scheme value, such as a percentage or letter.',['Check the Default Scheme and the range containing the learner’s numeric grade.','Inspect the student display options separately from the instructor’s personal options.'],'A numeric grade can stay unchanged while its displayed letter changes.','The numeric grade is correct but the letter grade is unexpected.')
});
FIELD_HELP.finalCanExceed=FIELD_HELP.canExceed;FIELD_HELP.showWeighted=FIELD_HELP.showPercent;
