/* Working practice views aligned to the supplied control inventory where captured. */
let pendingCalculation=null,wizard={step:0,draft:null};
function upgradePracticeState(){for(const c of state.courses){Object.assign(c.settings,{managingDecimals:c.settings.managingDecimals??2,showScheme:c.settings.showScheme??true,showCalculation:c.settings.showCalculation??false,schemeName:c.settings.schemeName??'Percentage',textLength:c.settings.textLength??15});c.personal??={showUsername:false,showOrgId:true,showPoints:false,showWeighted:true,showScheme:true,textLength:50,repeatColumns:5,repeatUsers:10};c.deletedItems??=[];for(const q of c.quizzes){if(!q.specialMode){for(const id of Object.keys(q.special))q.special[id]=q.minutes*q.special[id];q.specialMode='minutes';}}for(const a of c.assignments)a.special??={};}
 if(!state.courses.some(c=>c.id==='captured-empty')){const c=sampleCourse('captured-empty','Same Playground · practice copy','CAPTURE-EMPTY');Object.assign(c,{items:[],categories:[],grades:{},content:[],assignments:[],quizzes:[],scheme:[],deletedItems:[],capturedSeed:true});Object.assign(c.settings,{managingDecimals:2,decimals:2,showPoints:true,showPercent:true,showScheme:true,showCalculation:false,schemeName:'Percentage',textLength:15});c.personal={showUsername:false,showOrgId:false,showPoints:false,showWeighted:true,showScheme:true,textLength:50,repeatColumns:5,repeatUsers:10};state.courses.push(c);state.units.push({id:c.id,name:c.name,code:c.code,type:'Course Offering',parent:'dept'});}
}
upgradePracticeState();
ROUTES.push('course-offering');
view.adminOrder='category';
const COURSE_ADMIN_GROUPS=[
 ['Site Setup',['Availability Date Defaults','Course Offering Information','Homepages','Navigation & Themes','Widgets']],
 ['Site Resources',['Calendar','Content','Course Builder','Course Design Accelerator','External Learning Tools','Forms','Frequently Asked Questions','Glossary','Import / Export / Copy Components','Instructional Design Wizard','Learning Activity Library','Links','Manage Dates','Manage Files']],
 ['Learner Management',['Attendance','Class Progress','Classlist','Groups']],
 ['Assessment',['Assignments','Awards','Checklists','Competencies','Grades','Quick Eval','Quizzes','Rubrics','Self Assessments','Standards','Surveys']],
 ['Communication',['Announcements','Discussions','Intelligent Agents']],
 ['Administration',['Course Reset','Insights Portal','Sharing Groups','Tools']],
 ['Learning Repository',['Manage Repositories','Publish','Search']]
];
const ADMIN_ICON_KIND={
 'Availability Date Defaults':'calendar','Course Offering Information':'book','Homepages':'home','Navigation & Themes':'compass','Widgets':'widgets','Calendar':'calendar','Content':'openbook','Course Builder':'blocks','Course Design Accelerator':'designbook','External Learning Tools':'puzzle','Forms':'forms','Frequently Asked Questions':'faq','Glossary':'glossary','Import / Export / Copy Components':'arrows','Instructional Design Wizard':'wand','Learning Activity Library':'library','Links':'chain','Manage Dates':'dategear','Manage Files':'folder','Attendance':'person','Class Progress':'progress','Classlist':'list','Groups':'people','Assignments':'monitor','Awards':'award','Checklists':'list','Competencies':'triangle','Grades':'ruler','Quick Eval':'personpen','Quizzes':'quiz','Rubrics':'rubric','Self Assessments':'self','Standards':'target','Surveys':'clipboard','Announcements':'news','Discussions':'chat','Intelligent Agents':'pagegear','Course Reset':'eraser','Insights Portal':'pie','Sharing Groups':'sharing','Tools':'tools','Manage Repositories':'database','Publish':'publish','Search':'search'
};
function adminIcon(label){const kind=ADMIN_ICON_KIND[label]||'list';const shapes={
 calendar:'<rect x="3" y="5" width="18" height="17" rx="1" fill="#fff"/><path d="M3 5h18v4H3z" fill="#d76565"/><path d="M7 2v5m10-5v5" stroke="#7d8688" stroke-width="2"/><path d="M6 12h2v2H6zm5 0h2v2h-2zm5 0h2v2h-2zM6 17h2v2H6zm5 0h2v2h-2zm5 0h2v2h-2z" fill="#c9cfd0" stroke="none"/>',
 book:'<path d="M4 2h15v20H4z" fill="#9bad4d"/><path d="M4 2h3v20H4z" fill="#465e39"/><path d="M7 20h12" stroke="#dfdabc"/>',
 home:'<path d="m2 11 10-9 10 9" fill="#e6d5c8" stroke="#b77862" stroke-width="2"/><path d="M5 10v12h14V10" fill="#e7e2c9"/><path d="M10 14h5v8h-5z" fill="#adbf99"/>',
 compass:'<circle cx="12" cy="12" r="10" fill="#76b4d6"/><circle cx="12" cy="12" r="7" fill="#e8f4f7"/><path d="m16 7-3 8-6 3 3-8z" fill="#659aba" stroke="none"/>',
 widgets:'<path d="M2 3h20v19H2z" fill="#e6e9ec"/><path d="M2 3h20v4H2z" fill="#c8cdd0"/><path d="M5 10h5v9H5zm8 0h6v4h-6zm0 6h6v3h-6z" fill="#6394ba" stroke="none"/>',
 openbook:'<path d="M2 3h8l2 2 2-2h8v18h-9l-1 1-1-1H2z" fill="#73a8a4"/><path d="M5 5h5l2 2 2-2h5v14h-5l-2 1-2-1H5z" fill="#faf9ee"/><path d="M12 7v13"/>',
 blocks:'<path d="M2 3h14v14H2z" fill="#5189b5"/><path d="m2 3 4 4h10M6 7v14l-4-4" fill="#70afd2"/><rect x="11" y="11" width="11" height="11" rx="1" fill="#e4a047"/>',
 designbook:'<path d="M3 2h14v19H3z" fill="#91a34e"/><path d="M3 2h3v19H3z" fill="#4f633e"/><path d="m9 21 9-14 3 2-9 14-4 1z" fill="#deb764"/>',
 puzzle:'<path d="M3 11h5V7c-2-4 6-5 5 0v4h4V7l5 3-2 13L2 19z" fill="#545b5f" stroke="none"/>',
 forms:'<path d="M8 2h13v17H8z" fill="#8aaaca"/><path d="M5 5h13v17H5z" fill="#b2c881"/><path d="M2 8h13v15H2z" fill="#cf9a9d"/><path d="M5 12h7m-7 4h7m-7 4h5" stroke="#f3e6e3"/>',
 faq:'<path d="M3 2h18v21H3z" fill="#77b5dd"/><path d="M3 2h3v21H3z" fill="#466e8c"/><text x="14" y="17" text-anchor="middle" font-size="17" font-family="Arial" fill="white" stroke="none">?</text>',
 glossary:'<path d="M2 3h8l2 2 2-2h8v18h-9l-1 1-1-1H2z" fill="#c3c598"/><path d="M5 5h5v14H5zm9 0h5v14h-5z" fill="#fffbed"/><path d="M7 8h2m-2 4h2m-2 4h2m7-8h2m-2 4h2m-2 4h2"/>',
 arrows:'<path d="m12 2-6 6h4v5h4V8h4zm0 20 6-6h-4v-5h-4v5H6z" fill="#92b257" stroke="#819965"/>',
 wand:'<path d="m3 21 14-14 3 3L6 24z" fill="#858d8f"/><path d="m17 7 3-3 3 3-3 3z" fill="#dfcf7a"/><path d="M5 1v7M1 5h8m9 9v7m-4-3h8" stroke="#d1bd56" stroke-width="2"/>',
 library:'<path d="M2 6h7l2-3h8v17H2z" fill="#d4c48b"/><path d="m4 10 18-1-4 12H2z" fill="#efe8bf"/><path d="m17 12 6 11H11z" fill="#d55a65"/><path d="m17 16 2 5h-4z" fill="white"/>',
 chain:'<rect x="1" y="8" width="13" height="8" rx="4" fill="#c1c6c6"/><rect x="11" y="8" width="12" height="8" rx="4" fill="#c1c6c6"/><path d="M6 12h12" stroke="#848d90" stroke-width="2"/>',
 folder:'<path d="M2 7V4h8l2 3h10v15H2z" fill="#d7c68c"/><path d="M2 9h20v13H2z" fill="#e8dbaa"/>',
 person:'<circle cx="8" cy="5" r="3" fill="#72afd3"/><path d="M3 10h10l-2 12H5z" fill="#a4cee3"/><circle cx="17" cy="17" r="5" fill="#dae2e4"/><path d="M17 14v4h3" fill="none"/>',
 progress:'<path d="M2 3h20v4H2z" fill="#b8c69a"/><path d="M2 3h9v4H2z" fill="#6ca050"/><path d="M2 10h20v4H2z" fill="#e5dbc3"/><path d="M2 10h14v4H2z" fill="#dda25b"/><path d="M2 17h20v4H2z" fill="#cdd9e0"/><path d="M2 17h6v4H2z" fill="#729ec6"/>',
 list:'<path d="M3 2h18v21H3z" fill="#fbfcf6"/><path d="M6 6h3v3H6zm0 5h3v3H6zm0 5h3v3H6z" fill="#88a958" stroke="none"/><path d="M12 7h6m-6 5h6m-6 5h6" stroke="#acb3a7"/>',
 people:'<circle cx="8" cy="6" r="4" fill="#97bd65"/><circle cx="17" cy="6" r="4" fill="#dca452"/><path d="M1 13h12v9H1z" fill="#83bd61"/><path d="M12 13h11v9H12z" fill="#e4c963"/>',
 monitor:'<rect x="2" y="2" width="20" height="16" rx="1" fill="#66b2de"/><path d="M5 5h14v10H5z" fill="#d3edf8"/><path d="M10 18v3m4-3v3M5 22h14" stroke="#6696b4" stroke-width="2"/>',
 award:'<path d="m12 1 10 7-4 14H6L2 8z" fill="#63a5d2" stroke="#4c7090" stroke-width="2"/><path d="m12 6 2 4 4 1-3 3 1 4-4-2-4 2 1-4-3-3 4-1z" fill="white" stroke="none"/>',
 triangle:'<path d="m12 1 4 7H8z" fill="#72a1bf"/><path d="m8 9 9 0 4 6H4z" fill="#e7c45d"/><path d="m4 16 17 0 3 6H1z" fill="#bb4f4d" stroke="none"/>',
 ruler:'<path d="M2 2h7v21H2z" fill="#d4aa4c"/><path d="M2 6h4m-4 4h3m-3 4h4m-4 4h3" stroke="#8c763e"/><path d="m10 12 4 5L23 5l-8 16-7-6z" fill="#75a556" stroke="none"/>',
 personpen:'<circle cx="9" cy="6" r="4" fill="none" stroke="#676f72" stroke-width="3"/><path d="m7 10-4 12m8-11 1 10m-5-6 10-3m-3 10 8-15" fill="none" stroke="#676f72" stroke-width="3"/>',
 quiz:'<path d="M3 2h14l4 5v16H3z" fill="#f8fbfb"/><path d="M17 2v6h5" fill="#e5e8e9"/><text x="12" y="19" text-anchor="middle" font-size="17" font-family="Arial" fill="#61a4cf" stroke="none">?</text>',
 rubric:'<path d="M2 2h20v21H2z" fill="#b7c775"/><path d="M5 5h4v4H5zm6 0h4v4h-4zm6 0h3v4h-3zM5 11h4v4H5zm6 0h4v4h-4zm6 0h3v4h-3zM5 17h4v4H5zm6 0h4v4h-4zm6 0h3v4h-3z" fill="#dce1bc" stroke="#829157"/>',
 self:'<path d="M6 2h16v14H6z" fill="#f0f7fa"/><text x="15" y="13" text-anchor="middle" font-size="13" font-family="Arial" fill="#6aabc8" stroke="none">?</text><circle cx="6" cy="13" r="3" fill="#3c474c"/><path d="M2 17h8v5H2zM13 20h10" fill="#465055" stroke-width="2"/>',
 target:'<circle cx="12" cy="12" r="10" fill="none" stroke="#7d8788" stroke-width="2.5"/><circle cx="12" cy="12" r="6" fill="none" stroke="#7d8788" stroke-width="2"/><path d="m2 1 10 11" stroke="#657174" stroke-width="3"/>',
 clipboard:'<path d="M4 4h16v19H4z" fill="#dccdaf"/><path d="M6 7h12v13H6z" fill="#fffff5"/><rect x="8" y="1" width="8" height="5" rx="1" fill="#b4b9b8"/>',
 news:'<path d="M2 5h20v15H2z" fill="#e3e8e8"/><path d="M5 8h5v5H5z" fill="#afc1c7"/><path d="M12 8h7m-7 3h7m-14 5h14" stroke="#98a9ad"/>',
 chat:'<path d="M2 3h15v11H8l-4 4v-4H2z" fill="#78bce5"/><path d="M12 10h11v9h-3v4l-4-4h-4z" fill="#e9eff2"/>',
 eraser:'<path d="m2 13 10-11h5l6 7-12 14H8z" fill="#586465"/><path d="m2 13 5-5 9 9-5 6H8z" fill="#d8dfdc"/><path d="M12 23h11" stroke-dasharray="2 2"/>',
 pie:'<path d="M11 1A11 11 0 1 1 1 13h10z" fill="#4667b4"/><path d="M9 1A10 10 0 0 0 1 11h8z" fill="#c5d65b"/><path d="M9 13H1l6 8 5-8z" fill="#65a5d8"/>',
 sharing:'<circle cx="7" cy="5" r="3" fill="#8daf69"/><circle cx="18" cy="5" r="3" fill="#8971a5"/><path d="M1 11h11v11H1z" fill="#8cb968"/><path d="M13 11h10v11H13z" fill="#9777b6"/><path d="m8 16 4-3 4 3-4 3z" fill="#ecedb3"/>',
 tools:'<path d="m3 2 5 4-2 4L1 6l2 7h5l11 11 4-4L11 9V4z" fill="#aeb4b6"/><path d="m20 1 3 3-7 8-3-3zM11 10l3 3-9 10-4-4z" fill="#be6460"/>',
 database:'<ellipse cx="12" cy="5" rx="8" ry="4" fill="#e3ebed"/><path d="M4 5v14c0 5 16 5 16 0V5c0 5-16 5-16 0z" fill="#dde5e7"/><path d="M4 12c0 5 16 5 16 0m-16 6c0 5 16 5 16 0" fill="none"/>',
 publish:'<path d="M6 8h13v15H6z" fill="#fffbea"/><path d="M12 17V1m-5 6 5-6 5 6" fill="none" stroke="#c7af47" stroke-width="2"/>',
 search:'<circle cx="9" cy="9" r="7" fill="#d3e7e9" stroke="#a3b0b3" stroke-width="2.5"/><path d="m14 14 8 9" stroke="#7b949d" stroke-width="4"/>'
 };
 const gear='<g transform="translate(12 12)"><path d="m0-5 2-1 1 3 3 1-1 2 1 2-3 1-1 3-2-1-2 1-1-3-3-1 1-2-1-2 3-1 1-3z" fill="#607b7f"/><circle r="2" fill="white" stroke="none"/></g>';
 let content=shapes[kind];if(kind==='dategear')content=shapes.calendar+gear;if(kind==='pagegear')content=shapes.news+gear;
 return `<svg class="course-tool-icon" viewBox="0 0 24 24" fill="none" stroke="#a2aaa9" stroke-width=".8" aria-hidden="true">${content||shapes.list}</svg>`;
}
function courseAdmin(){const groups=view.adminOrder==='name'?[['',COURSE_ADMIN_GROUPS.flatMap(g=>g[1]).sort((a,b)=>a.localeCompare(b))]]:COURSE_ADMIN_GROUPS;return `<div class="course-administration"><h1>Course Administration</h1><div class="admin-order" aria-label="Order course administration tools">${action('Category','admin-order','data-order="category" aria-pressed="'+(view.adminOrder!=='name')+'"',view.adminOrder!=='name'?'selected':'')}${action('Name','admin-order','data-order="name" aria-pressed="'+(view.adminOrder==='name')+'"',view.adminOrder==='name'?'selected':'')}</div>${groups.map(([title,items])=>`<section class="course-tool-section">${title?`<h2>${title}</h2>`:''}<div class="course-tool-grid">${items.map(label=>`<button type="button" class="course-tool-link" data-action="course-tool" data-label="${h(label)}" title="${(t=>t?t.kind==='route'?'Open practice tool':'Open the captured screen':'Reference entry — destination not captured')(courseToolTarget(label))}">${adminIcon(label)}<span>${h(label)}</span></button>`).join('')}</div></section>`).join('')}<p class="course-admin-caption">Layout aligned to your supplied Course Administration screenshot. Icons are original approximations. Unmodeled destinations open a reference note.</p></div>`;}
function courseOfferingPage(){const c=course();return `<p class="eyebrow">Course Administration → Course Offering Information</p><h1>Course Offering Information</h1><p class="help">This destination was not captured. The form below models the course name, code, status, and dates for practice.</p><form data-form="course">${field('Course Offering Name','name',c.name,'text','required maxlength="90"')}${field('Course Offering Code','code',c.code,'text','required maxlength="40"')}<div data-target="course-availability">${check('Course is active','active',c.active)}${field('Start date','start',c.start,'datetime-local')}${field('End date','end',c.end,'datetime-local')}</div>${savebar('Save course information')}</form>`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='admin-order'){view.adminOrder=b.dataset.order;render();}if(b.dataset.action==='course-tool'){const label=b.dataset.label,target=courseToolTarget(label);if(target&&target.kind==='route')navigate(target.value);else if(target)openCapture(target.value);else openDialog(label,`<p>This tool appears in the captured Course Administration menu.</p><p>The destination and its behavior have not been modeled. Its place in the menu is preserved so you can learn where to find it.</p><div class="savebar">${action('View captured Course Administration','capture-open','data-id="course-admin"')}${action('Close','close-dialog')}</div>`);}});
const mappedTools={'Assignments':'assignments','Grades':'grades','Quizzes':'quizzes','Classlist':'classlist'};
// The capture records where every Course Admin link goes, so the menu follows it instead of a hand-kept list.
const capturedDestinations=Object.fromEntries((CAPTURE.screens.find(s=>s.id==='course-admin')?.transitions||[])
 .filter(t=>t.result_screen_id).map(t=>[t.control,t.result_screen_id]));
function courseToolTarget(label){const route=mappedTools[label]||(label==='Content'?'content':label==='Course Offering Information'?'course-offering':null);
 return route?{kind:'route',value:route}:capturedDestinations[label]?{kind:'capture',value:capturedDestinations[label]}:null;}
function capturedNavbarMenu(label){const m=CAPTURE.screens.find(s=>s.id==='navbar-menus').menus.find(m=>m.anchor===label),id='captured-'+label;return `<div class="dropdown"><button type="button" class="navitem" data-action="menu" data-menu="${h(id)}" aria-expanded="${view.menu===id}">${h(label)} ▾</button>${view.menu===id?`<div class="menu">${m.items.map(item=>mappedTools[item]?action(h(item),'navigate',`data-route="${mappedTools[item]}"`):action(h(item),'course-tool',`data-label="${h(item)}"`)).join('')}</div>`:''}</div>`;}
function header(){return `<header class="topbar"><div class="brandmark">Practice Campus</div><label class="sr-only" for="course-select">Practice course</label><select id="course-select" class="course-select" data-action="course">${state.courses.map(c=>`<option value="${h(c.id)}"${selected(c.id,course().id)}>${h(c.name)}</option>`).join('')}</select><div class="top-actions">${action('Learner view','navigate','data-route="preview"')}${action('Admin exercises','navigate','data-route="admin"')}${action('Resources & AI','navigate','data-route="resources"')}</div></header><nav class="navbar" aria-label="Course tools">${navButton('Course Home','home')}${navButton('Content','content')}${capturedNavbarMenu('Course Tools')}${capturedNavbarMenu('Assessments')}${capturedNavbarMenu('Communication')}${navButton('Help','resources')}${navButton('Course Admin','course-admin')}${capturedNavbarMenu('More')}</nav><div class="simstrip"><span><b>Practice simulation</b> · Capture reported ${CAPTURE.captured} · Synthetic data</span><span>${storageAvailable?'● Saved in this browser':'Storage unavailable — export notes'}</span></div>`;}
function gradePage(){const sub=view.tab,settings=['personal','display','calculation'].includes(sub);return `<div class="row between"><h1>${settings?({personal:'Personal Display Options',display:'Org Unit Display Options',calculation:'Calculation Options'})[sub]:sub==='finals'?'Final Grades':'Grades'}</h1>${action('Setup walkthrough','tour','data-id="grade-setup"')}</div><div class="grade-navigation">${tabs([['enter','Enter Grades'],['manage','Manage Grades'],['schemes','Schemes'],['wizard','Setup Wizard']],sub,'grade-tab')}<div class="actions">${action('⚙ Settings','grade-tab','data-tab="personal"')}${action('Help','capture-open','data-id="grades-settings-personal"')}</div></div>${settings?gradeSettings():sub==='enter'?enterGrades():sub==='manage'?manageGrades():sub==='schemes'?schemes():sub==='wizard'?wizardPage():sub==='finals'?finalGradesPage():enterGrades()}`;}
function enterGrades(){return `<div class="toolbar"><button disabled title="not modelled">Import</button><button disabled title="not modelled">Export</button><button disabled title="not modelled">Switch to Spreadsheet View</button><button disabled title="not modelled">More Actions ▾</button></div><div class="toolbar">${action('View Actions for Final Calculated Grade ▾','final-column-menu','data-target="final-column-actions"')}${view.menu==='final-column'?`<div class="actions">${action('Enter Grades','grade-tab','data-tab="finals"')}${action('View recorded menu','capture-open','data-id="grades-enter-grades"')}</div>`:''}</div>${baseEnterGrades()}<p class="help">The editable score grid and exemption controls are a teaching layout. The capture did not include entering scores or the appearance of an exempt cell. Use the screen library to see the captured column and learner menus.</p>`;}
function gradeSettings(){const s=course().settings;let body='';
 if(view.tab==='personal'){const p=course().personal;body=`<form data-form="personal-display"><h2>Managing View Display Options</h2><h3>User Details</h3>${check('Username','showUsername',p.showUsername)}${check('Org Defined ID','showOrgId',p.showOrgId)}<h3>Grade Details</h3>${check('Points grade','showPoints',p.showPoints)}${check('Weighted grade','showWeighted',p.showWeighted)}${check('Grade scheme symbol','showScheme',p.showScheme)}<label class="choice"><input type="checkbox" disabled title="not modelled">Grade scheme color</label>${field('Number of characters to display for text items','textLength',p.textLength,'number','min="1" max="200" required')}${field('Number of columns before user details repeat','repeatColumns',p.repeatColumns,'number','min="1" max="50" required')}${field('Number of users before column header repeats','repeatUsers',p.repeatUsers,'number','min="1" max="100" required')}<p class="help">Username and Org Defined ID control the sample score grid. Other preferences are recorded for practice; repeated headers, text-grade items, and scheme colors are not rendered.</p>${savebar()}</form>`;}
 else if(view.tab==='display')body=`<form data-form="org-display"><h2>Managing View Display Options</h2>${field('Number of decimal places to display · managing view','managingDecimals',s.managingDecimals,'number','min="0" max="4" step="1" required')}<h2>Student View Display Options</h2><h3>Grade Details</h3>${check('Points grade','showPoints',s.showPoints)}${check('Weighted grade','showPercent',s.showPercent)}${check('Grade scheme symbol','showScheme',s.showScheme)}<label class="choice"><input type="checkbox" disabled title="not modelled">Grade scheme color</label>${field('Number of decimal places to display · student view','decimals',s.decimals,'number','min="0" max="4" step="1" required')}${field('Number of characters to display for Text items','textLength',s.textLength,'number','min="1" max="200" required')}<h3>Final Grade Calculation</h3>${check('Display how final grade was calculated to users','showCalculation',s.showCalculation)}<h3>ePortfolio Artifacts</h3><label class="choice"><input type="checkbox" disabled title="not modelled">Allow users to add their grades to their ePortfolio</label><p class="help">Weighted grade displays the configured item weight and its earned contribution in this lab. The displayed contribution is not a complete reconstruction of interim normalization or category drops.</p>${savebar()}</form>`;
 else {body=prototypeGradeSettings();body=body.slice(body.indexOf('<form'));body=body.replace('In this lab, saving automatic release ON releases the selected final for all currently enrolled sample learners. Turning it OFF does not retract existing releases.','In this lab, automatic release is the default for new final-grade records. Existing release choices are preserved. Use Final Grades → Release All for existing learners; verify the real course’s release behavior separately.').replace('Automatically apply a grade of zero to missing submissions once overdue','Automatically apply a grade of zero (0) to missing submissions once an assessment becomes overdue');}
 return `${tabs([['personal','Personal Display Options'],['display','Org Unit Display Options'],['calculation','Calculation Options']],view.tab,'grade-tab')}${body}<div class="toolbar">${action('Close','grade-tab','data-tab="enter"')}</div>`;
}
function applyCalculationSettings(c,draft){Object.assign(c.settings,draft);if(c.settings.autoUpdate)recalculate(c);}
function calculationConfirm(step){const record=CAPTURE.screens.find(s=>s.id==='grades-settings-calculation-confirm-'+step).dialogs[0];openDialog(record.title,`<p>${h(record.text)}</p><p class="help">Reported MSU confirmation ${step} of 2. In this lab, No cancels the staged settings.</p><div class="savebar">${action('Yes','calculation-yes',`data-step="${step}"`,'primary')}${action('No','calculation-no')}</div>`);}
function wizardPage(){const c=course(),d=wizard.draft||clone(c.settings),step=wizard.step;
 if(step===0)return `<h2>Grades Setup Wizard</h2><p>Welcome to the Grades Setup Wizard!</p><h3>Current Grade Book Settings</h3>${settingsSummary(c.settings)}${action('Start','wizard-start','','primary')}`;
 if(step===8)return `<h2>Grade Options</h2><div class="stack">${action('Create a New Grade Category','category','data-id="new"','link-button')}${action('Create a New Grade Item','item-type','','link-button')}<button disabled title="not modelled">Import Grades</button>${action('Create a New Grade Scheme','new-scheme','','link-button')}${action('Manage Grade Items and Categories','grade-tab','data-tab="manage"','link-button')}${action('Enter Grades','grade-tab','data-tab="enter"','link-button')}</div>`;
 let body='';const heading=['','Choose Grading System','Final Grade Released','Grade Calculations','Choose Default Grade Scheme','Managing View Display Options','Student View Display Options','Grades Setup Summary'][step];
 if(step===1)body=`<div data-target="grading-system">${radio('mode','weighted',d.mode,'Weighted','Every category or item contributes a percentage of the final grade.')}${radio('mode','points',d.mode,'Points','Earned points divided by possible points.')}<label class="choice"><input type="radio" disabled title="not modelled">Formula</label></div>`;
 if(step===2)body=`${radio('finalType','calculated',d.finalType,'Calculated Final Grade')}${radio('finalType','adjusted',d.finalType,'Adjusted Final Grade')}${check('Automatically release final grade','autoRelease',d.autoRelease)}`;
 if(step===3)body=`${radio('blanks','drop',d.blanks,'Drop ungraded items')}${radio('blanks','zero',d.blanks,'Treat ungraded items as 0')}<label class="choice"><input type="checkbox" disabled title="not modelled">Automatically apply a grade of zero (0) to missing submissions once an assessment becomes overdue</label><p class="help">Changes to this setting only take effect on assessments with future due dates. Automatic zeros are reference-only in this lab.</p>${check('Automatically keep final grade updated','autoUpdate',d.autoUpdate)}`;
 if(step===4)body=`<h3>Organization Schemes</h3>${radio('schemeName','Percentage',d.schemeName,'Percentage')}${c.scheme.length?`<h3>Course Schemes</h3>${radio('schemeName','Practice scheme',d.schemeName,'Practice scheme')}`:''}`;
 if(step===5)body=field('Number of decimal places to display','managingDecimals',d.managingDecimals,'number','min="0" max="4" step="1" required');
 if(step===6)body=`<h3>Grade Details</h3>${check('Points grade','showPoints',d.showPoints)}${check('Weighted grade','showPercent',d.showPercent)}${check('Grade scheme symbol','showScheme',d.showScheme)}<label class="choice"><input type="checkbox" disabled title="not modelled">Grade scheme color</label>${field('Number of decimal places to display','decimals',d.decimals,'number','min="0" max="4" step="1" required')}${field('Number of characters to display for Text items','textLength',d.textLength,'number','min="1" max="200" required')}${check('Display final grade calculation to users','showCalculation',d.showCalculation)}`;
 if(step===7)body=settingsSummary(d);
 return `<p class="eyebrow">Step ${step} of 7</p><h2>Step ${step}: ${heading}</h2><form data-form="wizard">${body}<div class="savebar"><button type="submit" class="primary">${step===7?'Finish':'Continue'}</button>${action('Go Back','wizard-back')}${action('Cancel','wizard-cancel')}</div></form><p class="help">This lab stages wizard changes until Finish. Exact intermediate persistence in real D2L was not established by the capture.</p>`;
}
function settingsSummary(s){return `<div class="panel"><dl><dt>Grading System</dt><dd>${s.mode==='points'?'Points':'Weighted'}</dd><dt>Final Grade To Release</dt><dd>Release the ${s.finalType==='calculated'?'Calculated':'Adjusted'} Final Grade<br>${s.autoRelease?'Automatically release final grade':'Do not automatically release final grade'}</dd><dt>Grade Calculations</dt><dd>${s.blanks==='drop'?'Drop ungraded items':'Treat ungraded items as 0'}<br>${s.autoUpdate?'Automatically keep final grades updated':'Do not automatically keep final grades updated'}<br>Do not apply automatic zeros to missing submissions</dd><dt>Default Grade Scheme</dt><dd>${h(s.schemeName||'Percentage')}</dd><dt>Managing View</dt><dd>Display ${s.managingDecimals??2} decimal places</dd><dt>Student View</dt><dd>Display ${s.decimals} decimal places<br>${s.showCalculation?'Display':'Do not display'} the final grade calculation to users</dd></dl></div>`;}
function manageGrades(){const c=course(),total=c.categories.reduce((s,g)=>s+g.weight,0)+c.items.filter(i=>!i.categoryId&&!i.bonus&&!i.excluded).reduce((s,i)=>s+i.weight,0);const associated=i=>[...c.assignments,...c.quizzes].find(a=>a.gradeItem===i.id)?.name||'—';const row=i=>`<tr><td><input type="checkbox" class="bulk-item" value="${h(i.id)}"${checked((view.bulkItems||[]).includes(i.id))} aria-label="Select ${h(i.name)}"></td><td>${action(h(i.name),'item',`data-id="${h(i.id)}"`,'link-button')}${i.hidden?' <span class="tag off">Hidden</span>':''}${i.bonus?' <span class="tag">Bonus</span>':''}</td><td>Numeric</td><td>${h(associated(i))}</td><td>${i.max}</td><td>${c.settings.mode==='weighted'?i.weight+'%':'—'}</td></tr>`;
 return `<div class="toolbar">${action('New ▾','structure-menu','data-menu="grade-new"','primary')}${action('More Actions ▾','structure-menu','data-menu="grade-more"')}${action('Bulk Edit','bulk-edit','','link-button')}</div>${view.menu==='grade-new'?`<div class="inline-menu">${action('Item','item-type')}${action('Category','category','data-id="new"')}</div>`:''}${view.menu==='grade-more'?`<div class="inline-menu"><button disabled title="not modelled">Reorder</button>${action('View Event Log','grade-event-log')}${action('Make Visible to Users','bulk-visibility','data-hidden="false"')}${action('Hide from Users','bulk-visibility','data-hidden="true"')}${action('Delete','delete-grades')}</div>`:''}${c.settings.mode==='weighted'&&Math.abs(total-100)>.00001?`<div class="weight-warning">Note: 'Final Calculated Grade' sums to ${total}%, not 100%. Verify the total weight of all top level categories and items is 100%.</div>`:''}<div data-target="manage-categories"><div class="table-wrap" data-target="manage-items"><table><thead><tr><th>Select</th><th>Grade Item</th><th>Type</th><th>Association</th><th>Max. Points</th><th>Weight</th></tr></thead><tbody>${c.categories.map(g=>`<tr class="category-row"><td><input type="checkbox" class="bulk-category" value="${h(g.id)}"${checked((view.bulkCategories||[]).includes(g.id))} aria-label="Select category ${h(g.name)}"></td><td>${action(h(g.name),'category',`data-id="${h(g.id)}"`,'link-button')}</td><td></td><td></td><td>${c.items.filter(i=>i.categoryId===g.id&&!i.bonus).reduce((s,i)=>s+i.max,0)}</td><td>${g.weight}%</td></tr>${c.items.filter(i=>i.categoryId===g.id).map(row).join('')}`).join('')}${c.items.filter(i=>!i.categoryId).map(row).join('')}<tr><td></td><td>${action('Final Calculated Grade','final-properties','','link-button')}</td><td></td><td></td><td>${c.items.filter(i=>!i.bonus&&!i.excluded).reduce((s,i)=>s+i.max,0)}</td><td>${total}%</td></tr><tr><td></td><td>${action('Final Adjusted Grade','grade-tab','data-tab="finals"','link-button')}</td><td></td><td></td><td></td><td></td></tr></tbody></table></div></div><p class="help">New Category, bulk-edit, event-log restore, and final-property forms are functional teaching layouts; those forms were not captured. Category weights are stored explicitly. Distribution modes beyond those weights are not implemented.</p><details class="accordion"><summary>Supported calculation boundaries</summary><div><p>Points and weighted numeric items; blanks, zeros, exemptions, visibility, and exclusions; completed equal-point/equal-weight drop-lowest; complete 100%-weighted bonus cases; category and final Can Exceed caps.</p><p>Partial or exempt weighted bonus combinations and partial or unequal-item drops show a limitation rather than an invented final. Formula and other grade-item types, background zeros, activity synchronization, and exact institution rounding rules are not reproduced.</p></div></details>`;
}
function itemTypeChooser(){const s=CAPTURE.screens.find(s=>s.id==='grades-new-item-type');openDialog('New Item',`<div class="stack">${s.controls.filter(c=>c.group==='types').map(c=>`<div class="list-card">${c.label==='Numeric'?action('Numeric','item','data-id="new"','primary'):`<button disabled title="not modelled">${h(c.label)}</button>`}<p class="help">${h(c.notes||'')}</p></div>`).join('')}</div>`);}
function finalGradesPage(){const c=course();return `<div class="toolbar">${action('Final Grades ▾','final-title-menu')}${view.menu==='final-title'?`<div class="inline-menu"><button disabled title="not modelled">View Event Log</button>${action('Recalculate All','recalculate')}${action('Transfer All','transfer')}<button disabled title="not modelled">Clear All</button><button disabled title="not modelled">Add Feedback for All</button>${action('Release All','final-release-all','data-release="true"')}${action('Unrelease All','final-release-all','data-release="false"')}</div>`:''}</div><p class="help">Release All and Unrelease All stage checkboxes on this page. Save applies them. The released column type is selected in Calculation Options.</p><form data-form="final-release"><div class="table-wrap" data-target="release-controls"><table><thead><tr><th>User</th><th>Final Calculated Grade</th><th>Final Adjusted Grade (%)</th><th>Released</th></tr></thead><tbody>${learners(c).map(u=>{const f=finalRecord(c,u.id);return `<tr><td>${h(userName(u.id))}</td><td>${pct(displayedFinal(c,u.id))}</td><td><input name="adjusted:${u.id}" type="number" min="0" step="any" value="${f.adjusted??''}" aria-label="${h(userName(u.id))} adjusted final"></td><td><input type="checkbox" name="released:${u.id}"${checked(f.released)} aria-label="Release Final ${c.settings.finalType==='calculated'?'Calculated':'Adjusted'} Grade to ${h(userName(u.id))}"></td></tr>`;}).join('')}</tbody></table></div>${savebar()}</form>`;}
function schemes(){const c=course();return `<div class="toolbar">${action('New Scheme','new-scheme','','primary')}</div><h2>Organization Schemes</h2><div class="panel"><b>Percentage</b><p class="help">A percentage display. This is the captured organization scheme name.</p></div><h2>Course Schemes</h2>${c.scheme.length?prototypeSchemes():'<div class="blank">No course schemes. Create an example scheme to practice.</div>'}<form data-form="default-scheme">${selectField('Default Scheme','schemeName',[{value:'Percentage',label:'Percentage'},...(c.scheme.length?[{value:'Practice scheme',label:'Practice scheme'}]:[])],c.settings.schemeName)}${savebar('Save default scheme')}</form><p class="help">The working example is limited to numeric grade display. Selectbox grade items and assigned scheme values are not modeled.</p>`;}
function accommodationDialog(id){const e=course().enrollments[id];openDialog('Edit Accommodations',modalForm('accommodation-v2',id,`<h3>${h(userName(id))}</h3><h2>Quizzes</h2><h3>Timing</h3>${check('Modify Time Limit','modify',e.multiplier!==1||(e.extraMinutes||0)>0)}${radio('kind','multiplier',e.accommodationKind||'multiplier','Multiplier of original quiz time')}${field('Multiplier of original quiz time · times','multiplier',e.multiplier??1,'number','min="0.1" max="10" step="0.1" required')}${radio('kind','extra',e.accommodationKind||'multiplier','Extra time')}${field('Extra time · minute(s)','extraMinutes',e.extraMinutes??0,'number','min="0" max="1440" step="1" required')}<p class="help">Controls were captured, but saving and learner timing were not observed. Effective timing here is a documented simulation.</p>`));}
function specialDialog(id){const q=course().quizzes.find(q=>q.id===id);openDialog('Special Access',`<p>${h(q.name)}</p><p class="help">Allow selected users special access to this quiz</p>${action('Add Users to Special Access','quiz-special-users',`data-id="${h(id)}"`,'primary')}<div class="callout">Quiz special access uses a specific time limit in minutes. The multiplier is in Classlist accommodations.</div>`);}
function quizSpecialUsers(id){const q=course().quizzes.find(q=>q.id===id);closeDialog();openDialog('Add Special Access to Quiz - '+q.name,modalForm('special-v2',id,`<h3>Timing</h3><p><b>Override time limit → Set time limit → New Time Limit</b></p><p class="help">Enter minutes for each sample learner. Leave blank to remove that learner’s override and use their course accommodation. This condensed form models only the timing override.</p>${learners(course()).map(u=>field('New Time Limit · '+userName(u.id)+' · minute(s)','minutes:'+u.id,q.special[u.id]??'','number','min="1" max="1440" step="1"')).join('')}`));}
function quizDialog(id){const c=course(),q=c.quizzes.find(q=>q.id===id)||{name:'',minutes:30,attempts:1,visible:false,gradeItem:''};openDialog(id==='new'?'New Quiz':'Edit Quiz',modalForm('quiz',id,`<div class="activity-editor"><div>${field('Quiz Title','name',q.name,'text','required maxlength="100"')}${selectField('In Grade Book · stored link only','gradeItem',[{value:'',label:'Not in Grade Book'},...c.items.map(i=>({value:i.id,label:i.name}))],q.gradeItem)}<p class="help">Questions and quiz delivery are not modeled.</p></div><div><details open class="accordion"><summary>Timing & Display</summary><div>${field('Time Limit · minute(s)','minutes',q.minutes,'number','min="1" max="1440" step="1" required')}</div></details><details open class="accordion"><summary>Attempts & Completion</summary><div>${field('Attempts Allowed','attempts',q.attempts,'number','min="1" max="99" step="1" required')}</div></details>${check('Visible to learners · lab toggle','visible',q.visible)}</div></div><p class="help">The captured editor uses collapsible panels. This practice editor models a subset; open the screen library for all recorded controls.</p>`,'Save and Close'));}
function assignmentDialog(id){const c=course(),a=c.assignments.find(a=>a.id===id)||{name:'',instructions:'',visible:false,start:'',due:'',end:'',gradeItem:''};openDialog(id==='new'?'New Assignment':'Edit Assignment',modalForm('assignment',id,`<div class="activity-editor"><div>${field('Assignment Title','name',a.name,'text','required maxlength="100"')}${field('Due Date','due',a.due,'datetime-local')}<label class="field"><span>Instructions</span><textarea name="instructions" maxlength="10000">${h(a.instructions)}</textarea></label>${selectField('In Grade Book · stored link only','gradeItem',[{value:'',label:'Not in Grade Book'},...c.items.map(i=>({value:i.id,label:i.name}))],a.gradeItem)}</div><div><details open class="accordion"><summary>Availability Dates & Conditions</summary><div>${field('Start Date','start',a.start,'datetime-local')}${field('End Date','end',a.end,'datetime-local')}<p class="help">Release conditions are not modeled.</p></div></details>${check('Visible to learners · lab toggle','visible',a.visible)}</div></div>`,'Save and Close'));}
function assignmentSpecial(id){const a=course().assignments.find(a=>a.id===id);openDialog('Manage Special Access',modalForm('assignment-special',id,`<p>Allow users with special access to submit outside the normal availability dates for this folder</p><p class="help">This condensed practice form models date overrides per learner. Blank fields inherit the normal date.</p>${learners(course()).map(u=>`<details class="accordion"><summary>${h(userName(u.id))}</summary><div>${field('Start Date · '+userName(u.id),'start:'+u.id,a.special?.[u.id]?.start||'','datetime-local')}${field('Due Date · '+userName(u.id),'due:'+u.id,a.special?.[u.id]?.due||'','datetime-local')}${field('End Date · '+userName(u.id),'end:'+u.id,a.special?.[u.id]?.end||'','datetime-local')}</div></details>`).join('')}`));}
function effectiveMinutes(c,q,user){const override=q.special[user],en=c.enrollments[user]||{},extra=en.accommodationKind==='extra'?en.extraMinutes||0:0,factor=en.accommodationKind==='extra'?1:en.multiplier??1;return {factor:override!==undefined?override/q.minutes:factor,minutes:override!==undefined?override:q.minutes*factor+extra,source:override!==undefined?'Quiz special access':extra?'Course accommodation · extra minutes':factor!==1?'Course accommodation':'Base time',extra};}
function learnerGradeValue(c,item,score){const s=c.settings,parts=[];if(s.showPoints)parts.push(h(score)+' / '+item.max);if(s.showPercent&&s.mode==='weighted'){const cat=c.categories.find(g=>g.id===item.categoryId),possible=item.weight*(cat?cat.weight/100:1);parts.push((score/item.max*possible).toFixed(s.decimals)+' / '+possible.toFixed(s.decimals)+' weighted');}else if(s.showPercent)parts.push((100*score/item.max).toFixed(s.decimals)+'%');if(s.showScheme&&s.schemeName==='Practice scheme')parts.push(h(letter(c,100*score/item.max)));else if(s.showScheme&&!s.showPercent)parts.push((100*score/item.max).toFixed(s.decimals)+'%');return parts.join(' · ')||'Grade display disabled';}
function learnerCalculation(c,user){const result=calculate(c,user);return `<div class="panel"><h3>How the final grade is calculated · simulation</h3>${result.warnings.length?result.warnings.map(w=>`<p>${h(w)}</p>`).join(''):`<ul>${result.groups.map(g=>`<li>${h(g.name)}: ${(g.ratio*100).toFixed(2)}%${c.settings.mode==='weighted'?' · configured weight '+g.weight+'%':' · '+g.earned+' / '+g.possible+' points'}</li>`).join('')}</ul>`}<p class="help">This breakdown display is separate from releasing the selected final grade. Weighted item displays use configured weights; the final calculation applies the supported normalization and drop rules.</p></div>`;}
function assignmentDates(assignment,user){const special=assignment.special?.[user]||{};return {start:special.start||assignment.start,due:special.due||assignment.due,end:special.end||assignment.end};}
function selectedItems(){return [...document.querySelectorAll('.bulk-item:checked')].map(e=>e.value);}
function gradeEventLog(){const c=course();openDialog('View Event Log · simulated restore',`<p class="help">The Event Log screen was not captured. This practice log restores only numeric items deleted within this lab.</p>${c.deletedItems.length?c.deletedItems.map(i=>`<div class="list-card row between"><span>${h(i.item.name)} · removed ${h(new Date(i.date).toLocaleString())}</span>${action('Restore','restore-item',`data-id="${h(i.item.id)}"`)}</div>`).join(''):'<p>No deleted numeric items in the practice log.</p>'}`);}
document.addEventListener('submit',e=>{const form=e.target,kind=form.dataset?.form;const handled=['wizard','org-display','personal-display','final-release','accommodation-v2','special-v2','assignment-special','bulk-edit','final-properties','default-scheme'];if(!handled.includes(kind))return;e.preventDefault();e.stopImmediatePropagation();const fd=new FormData(form),str=k=>formValue(fd,k),yes=k=>fd.has(k),c=course();try{
 if(kind==='wizard'){const d=wizard.draft,step=wizard.step;if(step===1)d.mode=str('mode');if(step===2){d.finalType=str('finalType');d.autoRelease=yes('autoRelease');}if(step===3){d.blanks=str('blanks');d.autoUpdate=yes('autoUpdate');}if(step===4)d.schemeName=str('schemeName');if(step===5)d.managingDecimals=num(fd,'managingDecimals',0,4);if(step===6){d.showPoints=yes('showPoints');d.showPercent=yes('showPercent');d.showScheme=yes('showScheme');d.decimals=num(fd,'decimals',0,4);d.textLength=num(fd,'textLength',1,200);d.showCalculation=yes('showCalculation');}if(step===7){applyCalculationSettings(c,d);wizard.step=8;changed('Saved successfully · local simulation.');}else{wizard.step++;render();}return;}
 if(kind==='org-display')Object.assign(c.settings,{managingDecimals:num(fd,'managingDecimals',0,4),decimals:num(fd,'decimals',0,4),textLength:num(fd,'textLength',1,200),showPoints:yes('showPoints'),showPercent:yes('showPercent'),showScheme:yes('showScheme'),showCalculation:yes('showCalculation')});
 if(kind==='personal-display')Object.assign(c.personal,{showUsername:yes('showUsername'),showOrgId:yes('showOrgId'),showPoints:yes('showPoints'),showWeighted:yes('showWeighted'),showScheme:yes('showScheme'),textLength:num(fd,'textLength',1,200),repeatColumns:num(fd,'repeatColumns',1,50),repeatUsers:num(fd,'repeatUsers',1,100)});
 if(kind==='final-release'){const updates=learners(c).map(u=>({id:u.id,adjusted:str('adjusted:'+u.id)===''?null:num(fd,'adjusted:'+u.id),released:yes('released:'+u.id)}));for(const u of updates)Object.assign(finalRecord(c,u.id),{adjusted:u.adjusted,released:u.released});}
 if(kind==='accommodation-v2'){const en=c.enrollments[form.dataset.id],modify=yes('modify');Object.assign(en,{accommodationKind:str('kind'),multiplier:modify?num(fd,'multiplier',0.1,10):1,extraMinutes:modify?num(fd,'extraMinutes',0,1440):0});}
 if(kind==='special-v2'){const q=c.quizzes.find(q=>q.id===form.dataset.id),special={};for(const u of learners(c))if(str('minutes:'+u.id)!=='')special[u.id]=num(fd,'minutes:'+u.id,1,1440);q.special=special;q.specialMode='minutes';}
 if(kind==='assignment-special'){const a=c.assignments.find(a=>a.id===form.dataset.id),special={};for(const u of learners(c)){const v={start:str('start:'+u.id),due:str('due:'+u.id),end:str('end:'+u.id)};datesValid(v.start||a.start,v.end||a.end);if(v.start||v.due||v.end)special[u.id]=v;}a.special=special;}
 if(kind==='bulk-edit'){const updates=c.items.map(i=>({id:i.id,name:str('name:'+i.id),weight:num(fd,'weight:'+i.id)}));for(const v of updates)Object.assign(c.items.find(i=>i.id===v.id),v);}
 if(kind==='final-properties')c.settings.finalCanExceed=yes('finalCanExceed');
 if(kind==='default-scheme')c.settings.schemeName=str('schemeName');
 if(document.getElementById('dialog').open)closeDialog();changed();
 }catch(err){toast(err.message);}},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,c=course();try{
 if(a==='calculation-yes'){const p=pendingCalculation;if(!p)return;if(b.dataset.step==='1'){closeDialog();calculationConfirm(2);}else{const target=state.courses.find(x=>x.id===p.courseId);applyCalculationSettings(target,p.settings);pendingCalculation=null;closeDialog();changed('Saved successfully · local simulation.');}}
 else if(a==='calculation-no'){pendingCalculation=null;closeDialog();}
 else if(a==='wizard-start'){wizard={step:1,draft:clone(c.settings)};render();}
 else if(a==='wizard-back'){wizard.step=Math.max(0,wizard.step-1);render();}
 else if(a==='wizard-cancel'){wizard={step:0,draft:null};render();}
 else if(a==='structure-menu'){view.bulkItems=selectedItems();view.bulkCategories=[...document.querySelectorAll('.bulk-category:checked')].map(e=>e.value);view.menu=view.menu===b.dataset.menu?null:b.dataset.menu;render();}
 else if(a==='item-type'){if(document.getElementById('dialog').open)closeDialog();itemTypeChooser();}
 else if(a==='final-column-menu'){view.menu=view.menu==='final-column'?null:'final-column';render();}
 else if(a==='final-title-menu'){view.menu=view.menu==='final-title'?null:'final-title';render();}
 else if(a==='final-release-all'){document.querySelectorAll('form[data-form="final-release"] input[type="checkbox"]').forEach(x=>x.checked=b.dataset.release==='true');toast('Release checkboxes staged. Select Save to apply.');}
 else if(a==='new-scheme'){if(!c.scheme.length)c.scheme=[{name:'A',min:90},{name:'B',min:80},{name:'C',min:70},{name:'D',min:60},{name:'F',min:0}];view.tab='schemes';changed('An example course scheme was created. Edit its thresholds before use.');}
 else if(a==='accommodation-v2')accommodationDialog(b.dataset.id);
 else if(a==='quiz-special-users')quizSpecialUsers(b.dataset.id);
 else if(a==='assignment-special')assignmentSpecial(b.dataset.id);
 else if(a==='bulk-visibility'){const ids=selectedItems();if(!ids.length)throw Error('Select at least one grade item first.');for(const i of c.items)if(ids.includes(i.id))i.hidden=b.dataset.hidden==='true';changed();}
 else if(a==='bulk-edit')openDialog('Bulk Edit · practice subset',modalForm('bulk-edit','',c.items.map(i=>`<div class="panel">${field('Name · '+i.name,'name:'+i.id,i.name,'text','required')}${field('Weight · '+i.name,'weight:'+i.id,i.weight,'number','min="0" step="any" required')}</div>`).join('')));
 else if(a==='final-properties')openDialog('Final Calculated Grade · practice properties',modalForm('final-properties','',check('Can Exceed','finalCanExceed',c.settings.finalCanExceed)+'<p class="help">This form was not captured. The option controls the calculation cap in the simulator.</p>'));
 else if(a==='grade-event-log')gradeEventLog();
 else if(a==='delete-grades'){const ids=selectedItems(),cats=[...document.querySelectorAll('.bulk-category:checked')].map(e=>e.value);if(!ids.length&&!cats.length)throw Error('Select grade items or categories first.');if([...c.assignments,...c.quizzes].some(x=>ids.includes(x.gradeItem)))throw Error('Unlink associated assignments or quizzes before deleting those items.');openDialog('Delete Grade Items and Categories',`<p>Remove ${ids.length} numeric item(s) and ${cats.length} category/categories from this practice course?</p><p class="help">Deleted numeric items and their sample scores can be restored in this lab’s Event Log. Removing a category moves its remaining items to course level.</p><div class="savebar">${action('Delete','confirm-delete-grades',`data-items="${h(JSON.stringify(ids))}" data-categories="${h(JSON.stringify(cats))}"`,'danger')}${action('Cancel','close-dialog')}</div>`);}
 else if(a==='confirm-delete-grades'){const ids=JSON.parse(b.dataset.items),cats=JSON.parse(b.dataset.categories);for(const i of c.items.filter(i=>ids.includes(i.id)))c.deletedItems.push({item:clone(i),date:new Date().toISOString(),scores:Object.fromEntries(Object.entries(c.grades).map(([u,gs])=>[u,clone(gs[i.id]||{score:null,exempt:false})]))});c.items=c.items.filter(i=>!ids.includes(i.id));c.categories=c.categories.filter(g=>!cats.includes(g.id));for(const i of c.items)if(cats.includes(i.categoryId))i.categoryId=null;closeDialog();changed('Removed from the local practice gradebook.');}
 else if(a==='restore-item'){const i=c.deletedItems.find(i=>i.item.id===b.dataset.id);if(!i)throw Error('Deleted item not found.');const item=clone(i.item);if(!c.categories.some(g=>g.id===item.categoryId))item.categoryId=null;c.items.push(item);for(const [u,g]of Object.entries(i.scores)){c.grades[u]??={};c.grades[u][item.id]=g;}c.deletedItems=c.deletedItems.filter(x=>x!==i);closeDialog();changed('Numeric item restored in the practice lab.');}
 }catch(err){toast(err.message);}});
document.addEventListener('change',e=>{if(e.target.dataset.action==='course'){view.bulkItems=[];view.bulkCategories=[];wizard={step:0,draft:null};if(!course().items.length&&view.route==='grades')view.tab='wizard';render();}});
