/* Ticket matching retrieves curated material; it is not an AI diagnosis. */
let supportQuery='';
function searchSupport(query,limit=6){const stop=new Set(['the','and','for','but','can','cannot','not','how','that','with','this','have','from','student','students','learner','learners','instructor','faculty','please','help','need']);const words=query.toLowerCase().match(/[a-z0-9]+/g)||[];const terms=[...new Set(words.filter(w=>w.length>2&&!stop.has(w)).map(w=>w.replace(/s$/,'')))];return TICKETS.map(t=>{const text=[t.title,t.symptom,...t.keywords].join(' ').toLowerCase();const score=terms.reduce((sum,w)=>sum+(text.includes(w)?1:0),0)+t.keywords.reduce((sum,k)=>sum+(k.includes(' ')&&query.toLowerCase().includes(k.toLowerCase())?3:0),0);return {ticket:t,score};}).filter(t=>!query.trim()||t.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(t=>t.ticket);}
function ticketCard(t){return `<article class="ticket-card"><h3>${h(t.title)}</h3><p>${h(t.symptom)}</p><details><summary>Diagnosis and verification</summary><ol>${t.check.map(c=>`<li>${h(c)}</li>`).join('')}</ol><p><b>Key distinction:</b> ${h(t.distinction)}</p><p><b>Verify:</b> ${h(t.verify)}</p>${t.source?`<a href="${h(t.source)}" target="_blank" rel="noopener">Supporting documentation ↗</a>`:''}</details><div class="toolbar">${t.tourId?action('Open walkthrough','launch-working-tour',`data-id="${h(t.tourId)}"`,'primary'):''}${t.screenId?action('Open captured screen','capture-open',`data-id="${h(t.screenId)}"`):''}${t.tool?action('Tool explanation','ticket-tool-help',`data-tool="${h(t.tool)}"`):''}</div><small class="muted">${h({'working':'Includes a working local sequence','captured-reference':'Captured-screen reference; saved behavior may not be observed',documentation:'Documentation reference; destination not reproduced'}[t.coverage]||t.coverage)}</small></article>`;}
function supportPanel(){return `<form id="support-search-form"><label class="field"><span>Ticket or topic</span><textarea name="support-query" maxlength="2000" placeholder="For example: the student sees quiz grades but cannot see the final grade">${h(supportQuery)}</textarea></label><button class="primary" type="submit">Find relevant workflows</button></form><p class="small muted">Searches the local reference library. Results are possible matches, not a diagnosis. Ticket text stays in this page.</p><div id="support-results">${supportResults()}</div>`;}
function supportResults(){const found=searchSupport(supportQuery,supportQuery?6:3);return `<p class="small muted">${supportQuery?found.length+' matching references':'Common tickets'}</p>${found.length?found.map(ticketCard).join(''):'<p>No close match in this library. Try a setting name, browse the captured screens, or bring the ticket to your AI assistant for further research.</p>'}`;}
function supportTools(){return [{name:'search_support_reference',title:'Find D2L ticket references',description:'Search curated local support tickets, diagnosis steps, source URLs, walkthrough IDs, and captured-screen IDs. Returns possible references, not verified diagnosis or institution policy.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:1,maxLength:2000}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){const x=exactInput(input,['query']);if(typeof x.query!=='string'||!x.query.trim()||x.query.length>2000)throw Error('Use a nonempty query of at most 2,000 characters.');return {matches:searchSupport(x.query),referenceDate:CAPTURE.captured,simulation:true};}}];}
document.addEventListener('submit',e=>{if(e.target.id!=='support-search-form')return;e.preventDefault();supportQuery=new FormData(e.target).get('support-query').trim();document.getElementById('support-results').innerHTML=supportResults();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="ticket-tool-help"]');if(!b)return;const info=TOOL_HELP[b.dataset.tool];if(info)openDialog(b.dataset.tool,`<div class="tool-reference">${helpBody(info)}</div>`);});
